# Generated by Django 5.0.14 on 2025-06-03 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taphoa', '0002_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
