# Generated by Django 5.0.14 on 2025-06-11 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taphoa', '0003_remove_product_slug'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='review',
            table='taphoa_review',
        ),
    ]
