# Generated by Django 5.0.14 on 2025-06-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taphoa', '0006_alter_review_product_alter_review_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storereview',
            name='user',
        ),
        migrations.AddField(
            model_name='storereview',
            name='email',
            field=models.EmailField(default='noemail@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storereview',
            name='name',
            field=models.CharField(default='Người dùng ẩn danh', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storereview',
            name='comment',
            field=models.TextField(default='Không có bình luận'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='storereview',
            table=None,
        ),
    ]
