# Generated by Django 5.0.14 on 2025-06-11 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taphoa', '0007_remove_storereview_user_storereview_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
    ]
