# Generated by Django 5.0.14 on 2025-06-11 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taphoa', '0009_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
    ]
